name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Scan
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

  unit-tests:
    runs-on: ubuntu-latest
    needs: dependency-scan
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: echo "No tests yet"

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t secure-app:${GITHUB_SHA} .

  container-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Scan Image
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: secure-app:${{ github.sha }}
          severity: CRITICAL
          ignore-unfixed: true

  deploy:
    runs-on: ubuntu-latest
    needs: container-scan
    steps:
      - name: Deploy
        run: echo "Deploy successful"